### ISSUE TITLE
Add timeout alarm based on logs

### ISSUE THREAD

**Issue by AntonBazhal** [Brightspace/serverless-plugin-aws-alerts#5]
Should look something like:

```yaml
functionTimeout:
        namespace: logs
        metric: timeouts
        threshold: 0
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: 'Task timed out after'
```
